{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n  +4\n  -5", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE         +4\nE         -5\n\ntest_main.py:11: AssertionError"}, "start": 1603112109982, "stop": 1603112109998, "uuid": "9f9ecf41-cc63-40da-9ff6-5fe7e618041f", "historyId": "836c02fcef1ff2710be031aa8d84b519", "testCaseId": "62335933eaa07cc43d84c576b9534540", "fullName": "test_main#test_answer", "labels": [{"name": "suite", "value": "test_main"}, {"name": "host", "value": "GJSJ2669-L"}, {"name": "thread", "value": "2200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_main"}]}